<HTML>
<TITLE>A1 Collaboration: Cola++</title>
<BODY bgcolor=WHITE>
<hr>
<table width=100%>
<TR>
<TD align=left><img src=Cola++.gif height=100>
<TD align=center><H3>
<a href=http://www.kph.uni-mainz.de/A1>A1 Collaboration</a> <br>
<a href=http://www.kph.uni-mainz.de>Institut für Kernphysik</a><br>
<a href=http://www.uni-mainz.de>Universität Mainz</a>
</H3>
<TD align=right><img src=a1.gif height=100>
</table>
<HR>
<H1 align=center>Cola<sup>++</sup> Documentation</H1>
Cola<sup>++</sup> is the analysis package of the A1 collaboration.
These HTML pages provide the documentation for the SOURCE CODE of
the libraries. This documentation was built using the 
 doc++ source code documentation system. <p>

This is far from being complete, but I hope it already helps.<p>

A <a href=Cola++.ps>Postscript version</a> is also available.
<HR>
