<HTML><TITLE>OOPS Collaboration: ColaMIT</TITLE>
<BODY>
<HR>
<TABLE WIDTH=100%>
<TR>
<TD ALIGN=LEFT><IMG SRC=cola.gif HEIGHT=100>
<TD ALIGN=CENTER><H3>
<A HREF=http://www-lns.mit.edu/~OOPS/electronics.html>
OOPS Collaboration</A><BR>
<A HREF=http://mitbates.mit.edu>Bates Linear Accelerator Center</A><BR>
<A HREF=http://www-lns.mit.edu>MIT Laboratory for Nuclear Science</A>
</H3>
<TD ALIGN=RIGHT><IMG SRC=oops.gif HEIGHT=100>
</TABLE>
<HR>
<H1 ALIGN=CENTER>Cola<sup>++</sup> Documentation</H1>
This is our first attempt to use the doc++ source code documentation system 
for the MIT/Bates version of Cola++. This is far from beeing complete, but
we hope it already helps to find some documentation.<P>
<HR>
