<HTML><TITLE>Jefferson Lab: ColaJLab</TITLE>
<BODY>
<HR>
<TABLE WIDTH=100%>
<TR>
<TD ALIGN=LEFT><IMG SRC=cola.gif HEIGHT=100>
<TD ALIGN=CENTER><H3>
<A HREF=http://www.jlab.gov>Jefferson Lab</A><BR>
</H3>
<TD ALIGN=RIGHT><IMG SRC=cola.gif HEIGHT=100>
</TABLE>
<HR>
<H1 ALIGN=CENTER>Cola<sup>++</sup> Documentation</H1>
This is our first attempt to use the doc++ source code documentation system 
for the Jefferson Lab version of Cola++. This is far from beeing complete, but
we hope it already helps to find some documentation.<P>
<HR>
