/* Diese Datei enthaelt nur als einen Text den Prolog des Postscriptfiles */
"%%!EndComments\n"
"/Helvetica findfont dup length dict /newdict exch def\n"
"{1 index /FID ne {newdict 3 1 roll put} {pop pop} ifelse } forall\n"
"newdict /Encoding ISOLatin1Encoding put\n"
"/Helvetica newdict definefont pop\n"
"/m 	{moveto}      def 	/l 	{lineto}      def\n"
"/r 	{rlineto}     def	/rm 	{rmoveto}     def\n"
"/s 	{stroke}      def	/c 	{closepath}   def\n"
"/n 	{newpath}     def	/gs	{gsave}	      def\n"
"/gr	{grestore}    def	/sw	{stringwidth} def\n"
"/pp	{pop pop}     def	/ppp	{pop pop pop} def\n"
"/NaN   {0}      def\n"
"/Inf   {0}      def\n"
"/marker   {0.07}      def\n"
"/d1 	{n marker 0 360 arc fill}   def \n"
"/d2 	{n marker 0 360 arc s}      def \n"
"/d3 	{n m marker marker rm marker -2 mul 0 r 0 marker \n"
"        -2 mul r marker 2 mul 0 r c fill}      def \n"
"/d4 	{n m marker marker rm marker -2 mul 0 r 0 marker \n"
"        -2 mul r marker 2 mul 0 r c s}      def \n"
"/d5    {n m mark 0 rm mark neg mark r mark neg dup r \n"
"        mark mark neg r c fill} def\n" 
"/d6    {n m mark 0 rm mark neg mark r mark neg dup r\n"
"        mark mark neg r c s} def\n" 
"/d7    {n m 0 mark rm mark 30 cos mul mark -2 div r 0  mark neg r mark\n"
"        30 cos mul neg mark -2 div r mark 30 cos mul neg mark 2 div r\n" 
"	 0 mark r c fill} def\n"
"/d8    {n m 0 mark rm mark 30 cos mul mark -2 div r 0  mark neg r mark \n"
"        30 cos mul neg mark -2 div r mark 30 cos mul neg mark 2 div r\n" 
"	 0 mark r c s} def\n"
"/font	{findfont fs scalefont setfont} def\n"
"/left	{dup sw pop 3 index exch sub 2 index m show pp} def \n"
"/center {dup sw pop 2.0 div 3 index exch sub 2 index m show pp} def\n"
"/align  {dup sw pop 2 index mul 4 index exch sub 3 index m show ppp} def\n"
"/smallfont {lastfo 0.7 scalefont setfont /fs fs 0.6 mul def} def\n"
"/t1 {/tstart {gs currentpoint /yline 1 index def pp} def} def\n"
"/t2 {/tstop {show gr} def /saveold {show /lastfo currentfont def} def} def\n"
"/t3 {/lastfs fs def} def\n"
"/t4 {/supr {saveold 0 fs 2 div       rm smallfont} def} def\n"
"/t5 {/subs {saveold 0 0 fs 4 div sub rm smallfont} def} def\n"
"/t6 {/norm {show currentpoint pop yline m lastfo setfont /fs lastfs def} def} def\n"
"/t7 {/symb {show (Symbol) font} def} def\n"
"/t8 {/helv {show (Helvetica) font} def} def\n"
"/myshow {t1 t2 t3 t4 t5 t6 t7 t8} def \n"
"/t9  {/tstart {gs 0.0} def} def\n"
"/t10 {/tstop {sw pop add gr} def} def\n"
"/t11 {/saveold {sw pop add /lastfo currentfont def /lastfs fs def} def} def\n"
"/t12 {/supr {saveold smallfont} def} def\n"
"/t13 {/subs {saveold smallfont} def} def\n"
"/t14 {/norm {sw pop add lastfo setfont /fs lastfs def} def} def\n"
"/t15 {/symb {sw pop add (Symbol) font} def} def\n"
"/t16 {/helv {sw pop add (Helvetica) font} def} def\n"
"/mycount{t9 t10 t11 t12 t13 t14 t15 t16} def\n"
"/text	{m dup mycount exec 2 index neg mul 0 rm myshow exec pop} def\n"
"/marktext {m dup mycount exec dup 3 index neg mul fs -3 div rm \n"
"gs 0 fs -2 div rm dup 0 r 0 fs 1.5 mul r neg 0 r c 1 setgray fill\n"
"gr myshow exec pop} def\n"
"/dr	{7 copy m l l c gs setgray fill gr n m l s ppp} def\n"
"/sq	{m l l l c gs 1 setgray fill gr s} def\n"
"/hueSaturation {0 0} def\n"
"/gry {1 exch sub hueSaturation 2 index sethsbcolor pop n m 0 dy r dx 0 "
"      r 0 dy neg r c fill 0 setgray} def\n"
"/box {/gh exch def  n m dx 1 gh sub 2 div mul dy 1 gh sub 2 div mul\n"
"      rm /dxs dx gh mul def /dys dy gh mul def 0 dys r dxs 0 r 0 dys neg r\n"
"      c stroke} def\n"
"/clrbox {dup dup 360 mul sin 3 1 roll dup dup mul mul 3 1 roll\n"
"         sqrt 3 1 roll setrgbcolor \n"
"         n m -0.01 -0.01 rm 0 dy 0.02 add r dx 0.02 add 0  r 0 dy 0.02 add\n"
"         neg r c fill 0 setgray} def\n"
"/fseed 12345 def\n"
"/frand {fseed 1366 mul 150889 add 714025 mod \n"
"        dup /fseed exch def 714025 div } def \n"
"/sct {/gh exch def gs translate\n"
"      1 1 gh {pop frand dx mul frand dy mul m 0 0.01 r s} for gr} def\n"
"/bx {n m gs dup scale 0 dy r dx 0 r 0 dy neg r c s gr} def \n"






